---
title: "Ejercicios"
author: "Harold Garcia"
date: "18/11/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Parte 1

### 01
#### a

```{r} 
(0.3)*(0.15)/(0.3*0.15+0.2*0.8+0.5*0.12)
```
#### b
```{r} 
(5^6)*exp(-5)/factorial(6)
```
#### c
```{r} 
(factorial(20)/(factorial(7)*factorial(13)))*0.4^7*0.6^13
```
### 02
#### a
```{r} 
sum(1:1000)
```
#### b
```{r} 
((2^11)-1)/2-1
```
### 03
#### a
```{r} 
load(url("https://goo.gl/uDzU8v"))
```
```{r} 
length(grupo)
```
#### b
```{r} 
which(grupo=="A")
```
### 04
#### a
```{r} 
sum(nota)
```
#### b
```{r} 
mean(nota)
```
#### c
```{r} 
which(7.0 < nota)
```
#### d
```{r} 
sort(nota, decreasing = TRUE)
```
#### e
```{r} 
which(nota == max(nota))
```
### 05
#### a
```{r} 
 team14 <- data.frame(grupo, nota)
      team14
      head(team14,10)
      sum(head(team14$nota,10))
```
#### b
```{r} 
length(which(grupo == "C"))
```
#### c
```{r} 
length(which(nota > 5.0))
```
#### d
```{r} 
which(team14$grupo == "B"& team14$nota>5)
      length(which(grupo == "B" & nota>5))

```
#### e
```{r} 
(100*22)/39
      length(which(team14$grupo == "C" & team14$nota>5))/length(which(team14$grupo=="C"))*100
```
#### f
```{r} 
 which.max(nota)
      which.min(nota)
      nota[120]
      nota[142]
      grupo[120]
      grupo[142]

```
#### g
```{r} 
  which(team14$grupo == "A" & team14$nota>5) 
      which(team14$grupo == "B"& team14$nota>5)
      notas_A <- nota[ c(2,  17,  28, 108)]
      notas_B <- nota [c(13,  18,  65,  86, 103, 148, 170, 176, 186, 187)]
      mean(notas_A<-nota[ c(2,  17,  28, 108)])
      mean (nota[c(13,  18,  65,  86, 103, 148, 170, 176, 186, 187)])
      notas_C<-nota[c(2,  17,  28, 108, 13,  18,  65,  86, 103, 148, 170, 176, 186, 187)]
      mean(notas_C)
      
```
### 06
```{r} 
 66*length(nota)/100
    nota_ordenada <- sort(nota)
    nota_ordenada -> nota
    nota_ordenada[126]      
    nota_ordenada[127]  
```
### 07
```{r} 
 length(which(nota<=4.9))/length(nota)*100
    length(which(nota>=4.9))/length(nota)*100
    which(nota==4.9)
```
### 08
```{r} 
 boxplot(nota ~ grupo)
```
### 09
#### a
```{r} 
  max(conc)
```
#### b
```{r} 
 length(which(conc> 40.0))
```
#### c
```{r} 
mean(conc)
```
#### d
```{r} 
head(sort(conc),10)
```
#### e
```{r} 
 max(conc)
      conc[47.34]
      which(conc==max(conc))
      288/(24*60)
      # 1 muestra - 5 min
      # 142 es el maximo
      (83-8)/90*60
```
## Parte 2

### 01

```{r} 
  m <- 1:10
      q <- m^2
      plot(m,q)
```
### 02
```{r} 
matrix(c(1,2,3,2,4,6, 3,6,9,4,8,12),nrow = 4,ncol = 3,byrow = TRUE)
```
### 03
```{r} 
diag(3)
```
### 04
```{r} 
 F4 <- function(n) { I <- diag(n); for(i in 1:n){I[i,i]=0}; return(I)}
      F4(4)
```
### 05
```{r} 
D <-diag(4)
      D[1,1] = 0
      D[2,2] = 2
      D[3,3] = 3
      D[4,4] = 4
      D
```
### 06
```{r} 
t(matrix(c(1,2,3,2,4,6, 3,6,9,4,8,12),nrow = 4,ncol = 3,byrow = TRUE))
```
### 07
```{r} 
 A7 <- matrix(c(1,2,3,4,2,4,6,8,3,6,9,12,0,0,0,0), nrow = 4 , ncol = 4)
      B7 <- matrix(c(0,0,0,0,2,0,0,0,0,3,0,0,0,0,0,4), ncol=4)
      (A7+B7)
      (A7-B7)
      (A7*B7)
      (3*B7)
```
### 08
```{r} 
 F8<-function(M,n){S=M;for(i in 2:n){S=S%*%M};print(S)}
      P <- matrix(c(1,-2,1,2,4,0,3,-2,1), ncol=3, nrow=3)
      F8(P,6)
```
### 09
```{r} 
 A9 = matrix(c(3,9,3,-1,-2,1,1,1,-2), ncol=3,nrow=3)
      x9 <- c(-1,-9,-9)
      solve(A9,x9)
```
### 10
```{r} 
 ??eigen # Computes eigenvalues and eigenvectors of numeric 
              # (double, integer, logical) or complex matrices.
    
      ??det   # det calculates the determinant of a matrix. determinant 
              # is a generic function that returns separately the modulus 
              # of the determinant, optionally on the logarithm scale, and 
              # the sign of the determinant.
      
```
### 11
```{r} 
 M1 <- c(1:10)
      M2 <- seq(2, 20, by = 2)
      M3 <- seq(3, 30, by = 3)
      M4 <- seq(4, 40, by = 4)
      M5 <- seq(5, 50, by = 5)
      B11 = cbind(M1, M2, M3, M4, M5)
      B11
      
      N1 <- c(0,1,0,0,1)
      N2 <- c(1,0,1,1,0)
      N3 <- c(0,1,0,0,1)
      N4 <- c(1,0,1,0,1)
      N5 <- c(0,1,0,1,0)
      A11 = cbind(N1,N2,N3,N4,N5)
      A11
      B11%*%A11-B11%*%t(A11)
```
### 12
```{r} 
  x12 <- matrix(c(1,1,1,1,1,1,-1,0,1,2), nrow = 5, ncol = 2)
      y12 <- matrix(c(0,0,1,1,3), nrow = , ncol = 1)
      ((t(x12)%*%x12)^-1)%*%(t(x12)%*%y12)
      
```
### 13
#### a
```{r} 
   data(co2)
      means = aggregate(co2, FUN=mean)
      year = as.vector(time(means))
      co2 = as.vector(means)
```
#### b
```{r} 
co2
      year
```
#### c
```{r} 

```
#### d
```{r} 
 
```
#### e
```{r} 

```
### 14
#### a
```{r} 
rainfalldf <- read.csv("C:/Users/Usuario/Downloads/rainfall.csv")

rainfalldf
```
#### b
```{r} 

```
